### ISSUE TITLE
Beta error: Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by unional** [Orbs/jspm-git#30]
https://github.com/Orbs/jspm-git/blob/jspm-0.17/git.js#L481

Happens when I try to install package form a intranet bitbucket.

**Comment by subesokun** [comment]
Hi @unional Which beta version are you using of jspm and jspm-git?

**Comment by unional** [comment]
jspm: beta-11
jspm-git: beta-3

**Comment by subesokun** [comment]
Fixes but will be first released after the other PRs has been merged.

**Comment by subesokun** [comment]
Reopening this issue until new beta release has been drafted to avoid issue duplications.

**Comment by ggrimbert** [comment]
Same problem with JSPM 0.17.0-beta.22

**Comment by mcwillso** [comment]
@subesokun any update on this? Can we put only this fix in a 0.5.0-beta.4 release?

**Comment by subesokun** [comment]
Hi @mcwillso, sorry for the delay. I can't promise it but I'll try to get a release ready by next week.

**Comment by subesokun** [comment]
Patch has been release via v0.5.0-beta.4 🎉

**Comment by mcwillso** [comment]
@subesokun This is not working for me. Appears that options.auth and/or options.hostname is undefined and causes the following err(I am printing e.stack):
```
err TypeError: Cannot read property 'undefined' of undefined
    at readNetrc (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm-git/git.js:97:20)
    at Object.GitLocation (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm-git/git.js:289:17)
    at Object.exports.load (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm/lib/registry.js:92:56)
    at Object.locate (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm/lib/package.js:63:27)
    at /home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm/lib/install.js:205:16
    at tryCatcher (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/matt/gits/odin-web-ui/src/main/webapp/node_modules/jspm/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
Unhandled rejection Unable to  load registry %company-bitbucket%
```

File git.js:286
```
if (typeof options.auth == 'string') {
    this.auth = decodeCredentials(options.auth);
  } else {
    this.auth = readNetrc(options.hostname);
  }
```

**Comment by subesokun** [comment]
@mcwillso, sorry there as an issue with the netrc dependency. I've removed the netrc feature for now and release a new beta. Could you give it another try?

**Comment by mcwillso** [comment]
Working now. Thanks @subesokun!
