### ISSUE TITLE
jspm-git@beta breaks on log

### ISSUE THREAD

**Issue by hmps** [Orbs/jspm-git#38]
Trying to convert a project to JSPM 0.17 beta I ran into a problem with jspm-git.

```
err  Error on processPackageConfig
TypeError: Cannot read property 'log' of undefined
    at GitLocation.processPackageConfig (/Users/hape/Sites/apsis/Apsis.Cloud/node_modules/jspm-git/git.js:483:14)
    at /Users/hape/Sites/apsis/Apsis.Cloud/node_modules/jspm/lib/registry.js:133:30
    at tryCatcher (/Users/hape/Sites/apsis/Apsis.Cloud/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/hape/Sites/apsis/Apsis.Cloud/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/hape/Sites/apsis/Apsis.Cloud/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/Users/hape/Sites/apsis/Apsis.Cloud/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/Users/hape/Sites/apsis/Apsis.Cloud/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/hape/Sites/apsis/Apsis.Cloud/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/hape/Sites/apsis/Apsis.Cloud/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The issue is that `this.ui` is undefined in `processPackageConfig`:

```
// Line 466
if (noDepsMsg) {
          delete packageConfig.dependencies;
          delete packageConfig.peerDependencies;
          this.ui.log('warn', '`' + packageName + '` dependency installs skipped as it\'s a package with no registry property set.\n' + noDepsMsg + '\n');
        }

// Line 479
if (packageConfig.directories && packageConfig.directories.lib && !packageConfig.directories.dist) {
      packageConfig.directories.dist = packageConfig.directories.lib;
      this.ui.log('warn', 'Package `' + packageName + '` has a %directories.lib% override configuration which will work, but is deprecated for %directories.dist% in future jspm versions.\n');
    }
```

`ui` is passed into `GitLocation.configure`, but that method is never called in my case, and `ui` is not assigned to the instance anyway.

A quick way to solve it would be to add `ui` to the `options` object passed into the `GitLocation` constructor, but I guess that would change the interface of the package. Maybe this in combination with setting `this.ui = options.ui || console;`?

I'm happy to PR but would like to get your opinion first.

**Comment by subesokun** [comment]
Hi @hmps, the issue has been already fixed (see https://github.com/Orbs/jspm-git/issues/30) but I had no chance yet to make a new release :( Sorry for the troubles. I'll try to release a new `v0.5.0` beta as soon as I find time.

**Comment by hmps** [comment]
Oh, I'm sorry for the duplicate @subesokun! Thank you for replying so promptly!
